# GoReleaser configuration
# Run: goreleaser release --clean

version: 2

project_name: cf

before:
  hooks:
    - go mod tidy

builds:
  - id: cf
    main: ./cmd/cf
    binary: cf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/harshit-vibes/cf/pkg/cmd.Version={{.Version}}
      - -X github.com/harshit-vibes/cf/pkg/cmd.Commit={{.Commit}}
      - -X github.com/harshit-vibes/cf/pkg/cmd.BuildDate={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

# Homebrew tap (uncomment after creating harshit-vibes/homebrew-tap repo)
# brews:
#   - name: cf
#     repository:
#       owner: harshit-vibes
#       name: homebrew-tap
#     homepage: "https://github.com/harshit-vibes/cf"
#     description: "Codeforces CLI - competitive programming companion with TUI"
#     license: "MIT"
#     install: |
#       bin.install "cf"
#     test: |
#       system "#{bin}/cf", "version"
